<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8a2f0bf1-4228-41bd-a557-4363e48e7283</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="0.8.0-preview.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PraxisNote.Application\PraxisNote.Application.csproj" />
    <ProjectReference Include="..\PraxisNote.Infrastructure\PraxisNote.Infrastructure.csproj" />
  </ItemGroup>

</Project>
