export type MeetingStatus = 'Draft' | 'Processing' | 'Ready' | 'Reviewed' | 'Failed';

export interface MeetingTag {
  id: string;
  name: string;
}

export interface ActionItem {
  id: string;
  description: string;
  assignee: string | null;
  isCompleted: boolean;
  createdAt: string;
}

export interface Meeting {
  id: string;
  title: string | null;
  isTitleAutoGenerated: boolean;
  meetingDate: string | null;
  attendees: string | null;
  transcriptContent: string | null;
  status: MeetingStatus;
  summary: string | null;
  keyPoints: string | null;
  decisions: string | null;
  behavioralAnalysis: string | null;
  suggestedTags: string | null;
  reflectionData: string | null;
  reflectionSubmittedAt: string | null;
  excludeFromInsights: boolean;
  noteId: string | null;
  tags: MeetingTag[];
  actionItems: ActionItem[];
  createdAt: string;
  updatedAt: string;
}

// Behavioral Analysis Types
export interface BehavioralAnalysis {
  speakingDynamics: SpeakingDynamics;
  sentimentTone: SentimentTone;
  communicationPatterns: CommunicationPatterns;
  redFlags: RedFlag[];
}

export interface SpeakingDynamics {
  talkTimeByParticipant: ParticipantTalkTime[];
  interruptionPatterns: InterruptionPattern[];
  questionVsStatementRatio: Record<string, number>;
}

export interface ParticipantTalkTime {
  participant: string;
  percentage: number;
  duration: string;
}

export interface InterruptionPattern {
  interrupter: string;
  interrupted: string;
  count: number;
}

export interface SentimentTone {
  participantSentiments: ParticipantSentiment[];
  toneShifts: ToneShift[];
  emotionalIndicators: string[];
}

export interface ParticipantSentiment {
  participant: string;
  sentiment: 'positive' | 'neutral' | 'negative';
  score: number;
}

export interface ToneShift {
  timestamp: string;
  description: string;
  from: string;
  to: string;
}

export interface CommunicationPatterns {
  overallClarity: number;
  followUpPatterns: FollowUpPattern[];
  engagementLevels: ParticipantEngagement[];
}

export interface FollowUpPattern {
  topic: string;
  wasFollowedUp: boolean;
  assignedTo: string | null;
}

export interface ParticipantEngagement {
  participant: string;
  level: 'high' | 'medium' | 'low';
  indicators: string[];
}

export interface RedFlag {
  type: 'evasive' | 'hedging' | 'defensive' | 'inconsistent';
  participant: string;
  description: string;
  context: string;
  severity: 'low' | 'medium' | 'high';
}

export function parseJsonArray(json: string | null): string[] {
  if (!json) return [];
  try {
    const parsed = JSON.parse(json);
    if (!Array.isArray(parsed)) return [];
    return parsed.filter((item): item is string => typeof item === 'string');
  } catch {
    return [];
  }
}

/** Whether a meeting has any analysis results (summary, key points, decisions, or Ready status). */
export function hasAnalysisResults(meeting: Meeting | null | undefined): boolean {
  if (!meeting) return false;
  return !!meeting.summary?.trim() ||
    parseJsonArray(meeting.keyPoints).length > 0 ||
    parseJsonArray(meeting.decisions).length > 0 ||
    meeting.status === 'Ready';
}

export function parseBehavioralAnalysis(json: string | null): BehavioralAnalysis | null {
  if (!json) return null;
  try {
    const parsed = JSON.parse(json) as BehavioralAnalysis;
    // Basic validation - check if it has the expected structure
    if (parsed && typeof parsed === 'object' && 'speakingDynamics' in parsed) {
      return parsed;
    }
    return null;
  } catch {
    return null;
  }
}

export interface MeetingGroup {
  label: string;
  subLabel: string;
  meetings: Meeting[];
}

export interface ActionItemStatus {
  actionItemId: string;
  isLinked: boolean;
  taskId: string | null;
  taskStatus: 'Todo' | 'InProgress' | 'Done' | null;
}

export interface PromoteActionItemResult {
  taskId: string;
  title: string;
  status: string;
}

// Reflection Types
export interface ReflectionPrompt {
  promptId: string;
  category: 'talk-time' | 'engagement' | 'tone' | 'interruptions' | 'general';
  promptText: string;
  quickOptions: string[];
}

export interface PromptResponse {
  promptId: string;
  promptText: string;
  response: string;
}

export interface MeetingReflection {
  selfAssessedTalkTime: number | null;
  selfAssessedEngagement: string | null;
  selfAssessedTone: string | null;
  interruptionAwareness: string | null;
  freeformReflection: string | null;
  promptResponses: PromptResponse[];
}

export function parseReflection(json: string | null): MeetingReflection | null {
  if (!json) return null;
  try {
    const parsed = JSON.parse(json) as MeetingReflection;
    if (parsed && typeof parsed === 'object' && 'promptResponses' in parsed) {
      return parsed;
    }
    return null;
  } catch {
    return null;
  }
}

// Quick Reflection Types
export type EmojiLevel = 'low' | 'medium' | 'high';

export interface QuickReflectionValue {
  talkTime: EmojiLevel | null;
  engagement: EmojiLevel | null;
  tone: EmojiLevel | null;
  interruptions: EmojiLevel | null;
  freeformNote: string | null;
}

export interface QuickReflectionDimension {
  id: 'talkTime' | 'engagement' | 'tone' | 'interruptions';
  label: string;
  emojis: {
    low: { emoji: string; label: string };
    medium: { emoji: string; label: string };
    high: { emoji: string; label: string };
  };
}

export const QUICK_REFLECT_DIMENSIONS: QuickReflectionDimension[] = [
  {
    id: 'talkTime',
    label: 'Talk time',
    emojis: {
      low: { emoji: '🤐', label: 'Quiet' },
      medium: { emoji: '😐', label: 'Balanced' },
      high: { emoji: '🗣️', label: 'Dominated' },
    },
  },
  {
    id: 'engagement',
    label: 'Engagement',
    emojis: {
      low: { emoji: '😴', label: 'Low' },
      medium: { emoji: '😊', label: 'Engaged' },
      high: { emoji: '🔥', label: 'Highly' },
    },
  },
  {
    id: 'tone',
    label: 'Tone',
    emojis: {
      low: { emoji: '😠', label: 'Tense' },
      medium: { emoji: '😐', label: 'Neutral' },
      high: { emoji: '😊', label: 'Positive' },
    },
  },
  {
    id: 'interruptions',
    label: 'Interruptions',
    emojis: {
      low: { emoji: '✅', label: 'None' },
      medium: { emoji: '⚠️', label: 'Some' },
      high: { emoji: '🚨', label: 'Frequent' },
    },
  },
];

/** Maps emoji level values to Johari classification format */
export function mapQuickReflectToJohari(quick: QuickReflectionValue): {
  selfAssessedTalkTime: number | null;
  selfAssessedEngagement: string | null;
  selfAssessedTone: string | null;
  interruptionAwareness: string | null;
} {
  return {
    selfAssessedTalkTime: quick.talkTime
      ? quick.talkTime === 'low' ? 20 : quick.talkTime === 'medium' ? 50 : 80
      : null,
    selfAssessedEngagement: quick.engagement
      ? quick.engagement === 'low' ? 'Disengaged' : quick.engagement === 'medium' ? 'Moderate' : 'Highly Engaged'
      : null,
    selfAssessedTone: quick.tone
      ? quick.tone === 'low' ? 'Tense' : quick.tone === 'medium' ? 'Neutral' : 'Collaborative'
      : null,
    interruptionAwareness: quick.interruptions
      ? quick.interruptions === 'low' ? 'No' : quick.interruptions === 'medium' ? 'Partially' : 'Yes'
      : null,
  };
}
