import {
  Component,
  ChangeDetectionStrategy,
  inject,
  signal,
  computed,
  effect,
  OnInit,
  OnDestroy,
  AfterViewInit,
  HostListener,
  TemplateRef,
  viewChild,
  Injector,
  DestroyRef,
} from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subject, debounceTime, takeUntil } from 'rxjs';
import { Meeting, MeetingTag, ActionItemStatus, parseJsonArray } from './meeting.model';
import { MeetingService } from './meeting.service';
import { MeetingAnalysisComponent } from './meeting-analysis.component';
import { MeetingReflectionComponent } from './meeting-reflection.component';
import { MeetingSectionComponent } from './meeting-section.component';
import { MeetingDetailsSectionComponent } from './meeting-details-section.component';
import { MeetingTranscriptSectionComponent } from './meeting-transcript-section.component';
import { AudioRecorderService } from './audio-recorder.service';
import { DeepgramTranscriptionService } from './deepgram-transcription.service';
import { ToastService } from '../shared/services/toast.service';
import { BreadcrumbItem, ContextualHeaderService } from '../shared/services/contextual-header.service';
import { TagService } from '../tags/tag.service';
import { Tag } from '../tags/tag.model';
import { parseTimeInput, formatTimeLabel, getDefaultMeetingTime } from './meeting-time.utils';
import { toLocalISOString, formatShortDate } from '../shared/date-utils';
import { AuthService } from '../auth/auth.service';
import { DeleteConfirmationService } from '../shared/services/delete-confirmation.service';
import { DeleteConfirmButtonComponent } from '../shared/components/delete-confirm-button.component';
import { ButtonModule } from 'primeng/button';

interface DateOption {
  label: string;
  getValue: () => Date;
}

@Component({
  selector: 'app-meeting-editor-page',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [DeleteConfirmationService],
  imports: [
    MeetingSectionComponent,
    MeetingDetailsSectionComponent,
    MeetingTranscriptSectionComponent,
    MeetingAnalysisComponent,
    MeetingReflectionComponent,
    DeleteConfirmButtonComponent,
    ButtonModule,
  ],
  template: `
    <div class="meeting-editor-page">
      <!-- Actions template (rendered by app shell top bar) -->
      <ng-template #headerActions>
        <span class="flex items-center gap-1.5 text-xs text-foreground-muted pr-2" [class.text-accent-foreground]="isSaving()" role="status" aria-live="polite">
          @if (isSaving()) {
            <i class="pi pi-spin pi-spinner text-xs" aria-hidden="true"></i> <span class="hidden md:inline">Saving...</span>
          } @else if (lastSaved()) {
            <i class="pi pi-check text-done-foreground"></i> <span class="hidden md:inline text-done-foreground">Saved</span>
          }
        </span>
        @if (meetingId()) {
          @if (confirmingDelete()) {
            <app-delete-confirm-button
              ariaLabel="Confirm delete meeting"
              (onConfirm)="confirmDelete()"
            />
          } @else {
            <button type="button" class="w-9 h-9 flex items-center justify-center hover:bg-surface-muted rounded-lg text-foreground-secondary touch-target" (click)="startDeleteConfirm()" aria-label="Delete meeting" title="Delete meeting">
              <i class="pi pi-trash text-sm" aria-hidden="true"></i>
            </button>
          }
        }
      </ng-template>

      <!-- Scrollable content -->
      <main class="editor-container">
        @if (loading()) {
          <div class="loading" role="status" aria-label="Loading meeting">
            <i class="pi pi-spin pi-spinner text-2xl text-foreground-muted" aria-hidden="true"></i>
            <span class="sr-only">Loading meeting...</span>
          </div>
        } @else if (notFound()) {
          <div class="not-found">
            <i class="pi pi-exclamation-triangle text-4xl text-foreground-muted mb-4"></i>
            <p class="text-foreground-secondary">Meeting not found</p>
            <button
              type="button"
              class="mt-4 px-4 py-2 text-sm bg-accent-solid text-white rounded-md"
              (click)="navigateBack()"
            >
              Back to {{ sourceBreadcrumb().label }}
            </button>
          </div>
        } @else {
          <div class="max-w-6xl mx-auto px-6 md:px-8 py-8 md:py-10">
            <!-- Title -->
            <div class="title-row">
              <input
                class="title-input"
                type="text"
                placeholder="Meeting title..."
                [value]="title()"
                (input)="onTitleChange(asInput($event).value)"
                aria-label="Meeting title"
              >
              @if (isTitleAutoGenerated()) {
                <i class="pi pi-sparkles title-sparkle" title="AI-generated title"></i>
              }
            </div>

            <!-- Details Section (collapsible) -->
            <app-meeting-section
              #detailsSection
              title="Details"
              icon="pi-info-circle"
              [borderColor]="'var(--color-meeting-details-border)'"
              [headerColor]="'var(--color-todo-text)'"
              sectionId="details-section"
              [collapsible]="true"
            >
              <!-- Collapsed summary -->
              <div summary class="details-mini-card">
                <div class="mini-card-row">
                  <i class="pi pi-calendar text-[10px] text-foreground-muted"></i>
                  <span class="text-xs text-foreground-secondary">{{ dateSummary() }}</span>
                  <span class="text-xs text-foreground-muted">{{ timeSummary() }}</span>
                </div>
                <div class="mini-card-row">
                  <i class="pi pi-users text-[10px] text-foreground-muted"></i>
                  <span class="text-xs text-foreground-secondary">{{ attendeesSummary() }}</span>
                  @if (tagCountSummary()) {
                    <span class="mini-card-divider"></span>
                    <i class="pi pi-tag text-[10px] text-foreground-muted"></i>
                    <span class="text-xs text-foreground-secondary">{{ tagCountSummary() }}</span>
                  }
                </div>
              </div>

              <!-- Expanded content -->
              <app-meeting-details-section
                #detailsSectionRef
                [isNewMeeting]="isNewMeeting()"
                [meetingDate]="meetingDate()"
                [attendees]="attendees()"
                [meetingTags]="meetingTags()"
                [pendingSuggestedTags]="pendingSuggestedTags()"
                [includeInInsights]="includeInInsights()"
                [selectedDateChip]="selectedDateChip()"
                [customDateLabel]="customDateLabel()"
                [selectedTimeLabel]="selectedTimeLabel()"
                [timeInputInvalid]="timeInputInvalid()"
                [showDatePicker]="showDatePicker()"
                (onAttendeesChange)="onAttendeesChange($event)"
                (onDateOptionSelect)="selectDateOption($event)"
                (onDatePickerToggle)="toggleDatePicker()"
                (onDatePickerSelect)="onDatePickerChange($event)"
                (onTimeChanged)="onTimeChange($event)"
                (onRemoveTag)="removeTag($event)"
                (onAddTag)="addTag($event)"
                (onCreateAndAddTag)="createAndAddTag($event)"
                (onAcceptSuggestedTag)="acceptSuggestedTag($event)"
                (onDismissSuggestedTag)="dismissSuggestedTag($event)"
                (onToggleExcludeFromInsights)="onToggleExcludeFromInsights()"
                (onCloseDatePicker)="showDatePicker.set(false)"
              />
            </app-meeting-section>

            @if (!isNewMeeting()) {
              <!-- Transcript Section (hero element, always expanded) -->
              <app-meeting-section
                title="Transcript"
                icon="pi-file-edit"
                [borderColor]="'var(--color-meeting-transcript-border)'"
                [headerColor]="'var(--color-primary-text)'"
                sectionId="transcript-section"
                [collapsible]="false"
              >
                <app-meeting-transcript-section
                  [transcript]="transcript()"
                  [showTabWarning]="showTabWarning()"
                  (onTranscriptChange)="onTranscriptChange($event)"
                  (onStartRecording)="startRecording($event)"
                  (onStopRecording)="stopRecording()"
                />
              </app-meeting-section>

              <!-- AI Analysis Section -->
              <app-meeting-section
                #analysisSection
                title="AI Analysis"
                icon="pi-sparkles"
                [borderColor]="'var(--color-meeting-analysis-border)'"
                [headerColor]="'var(--color-done-text)'"
                sectionId="analysis-section"
              >
                <p-button
                  headerAction
                  [label]="analysisHasResults() ? 'Re-analyze' : 'Analyze'"
                  icon="pi pi-sparkles"
                  size="small"
                  [loading]="analysisIsProcessing()"
                  [disabled]="!analysisHasTranscript()"
                  (onClick)="analyze()"
                />
                @if (currentMeeting()) {
                  <app-meeting-analysis
                    [meeting]="currentMeeting()!"
                    [actionItemStatuses]="actionItemStatuses()"
                    [promotingIds]="promotingIds()"
                    (onToggleActionItem)="toggleActionItem($event)"
                    (onPromoteActionItem)="promoteActionItem($event)"
                    (onNavigateToTask)="navigateToTask($event)"
                  />
                }
              </app-meeting-section>

              <!-- Reflection Section (only when behavioral analysis exists) -->
              @if (currentMeeting()?.behavioralAnalysis) {
                <app-meeting-section
                  title="Self-Reflection"
                  icon="pi-comments"
                  [borderColor]="'var(--color-meeting-reflection-border)'"
                  [headerColor]="'var(--color-meeting-reflection-border)'"
                  sectionId="reflection-section"
                >
                  <app-meeting-reflection
                    [meeting]="currentMeeting()!"
                  />
                </app-meeting-section>
              }
            }
          </div>
        }
      </main>

      <!-- Footer -->
      <footer class="footer">
        @if (currentMeeting()) {
          <span class="text-xs text-foreground-muted">
            Last edited {{ formatDate(currentMeeting()!.updatedAt) }}
          </span>
        }
      </footer>
    </div>
  `,
  styles: [`
    .meeting-editor-page {
      display: flex;
      flex-direction: column;
      height: 100%;
      background: var(--color-bg-base);
    }

    :host {
      display: block;
      height: 100%;
    }

    .editor-container { flex: 1; overflow: auto; }
    .loading, .not-found { display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100%; }
    .title-row { display: flex; align-items: center; gap: 8px; margin-bottom: 20px; }
    .title-input {
      font-size: 22px; font-weight: 700; border: none; background: transparent;
      padding: 0; flex: 1; outline: none; color: var(--color-text-primary);
    }
    .title-input::placeholder { color: var(--color-text-muted); }
    .title-sparkle { color: var(--color-primary-solid); font-size: 14px; flex-shrink: 0; }

    .footer { display: flex; align-items: center; padding: 8px 24px; border-top: 1px solid var(--color-border-default); background: var(--color-bg-base); }

    /* Details mini card (collapsed summary) */
    .details-mini-card {
      display: flex;
      flex-direction: column;
      gap: 4px;
    }

    .mini-card-row {
      display: flex;
      align-items: center;
      gap: 6px;
    }

    .mini-card-divider {
      width: 1px;
      height: 10px;
      background: var(--color-border-default);
      flex-shrink: 0;
    }
  `],
})
export class MeetingEditorPage implements OnInit, AfterViewInit, OnDestroy {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly meetingService = inject(MeetingService);
  private readonly tagService = inject(TagService);
  private readonly toast = inject(ToastService);
  private readonly headerService = inject(ContextualHeaderService);
  private readonly auth = inject(AuthService);
  private readonly injector = inject(Injector);
  private readonly deleteConfirmation = inject(DeleteConfirmationService);
  private readonly destroyRef = inject(DestroyRef);
  readonly recorder = inject(AudioRecorderService);
  readonly transcription = inject(DeepgramTranscriptionService);

  private readonly destroy$ = new Subject<void>();
  private readonly metadataChange$ = new Subject<void>();
  private readonly transcriptChange$ = new Subject<void>();

  // View children
  readonly headerActions = viewChild<TemplateRef<unknown>>('headerActions');
  readonly detailsSection = viewChild<MeetingSectionComponent>('detailsSection');
  readonly detailsSectionRef = viewChild<MeetingDetailsSectionComponent>('detailsSectionRef');
  readonly analysisSection = viewChild<MeetingSectionComponent>('analysisSection');

  // Core state
  readonly loading = signal(true);
  readonly notFound = signal(false);
  readonly isNewMeeting = signal(false);
  readonly isSaving = signal(false);
  readonly lastSaved = signal(false);
  readonly meetingId = signal<string | null>(null);

  // Delete confirmation state
  readonly confirmingDelete = signal(false);

  // Form state
  readonly title = signal('');
  readonly meetingDate = signal<Date | null>(null);
  readonly attendees = signal('');
  readonly transcript = signal('');
  readonly showTabWarning = signal(false);

  // Date selection
  readonly selectedDateChip = signal<string | null>('Today');
  readonly customDateLabel = signal<string | null>(null);
  readonly showDatePicker = signal(false);

  // Time selection
  readonly selectedTimeLabel = signal('10:00 AM');
  readonly timeInputInvalid = signal(false);

  // Analysis state
  readonly actionItemStatuses = signal<ActionItemStatus[]>([]);
  readonly promotingIds = signal<Set<string>>(new Set());

  // Auto-generated title state
  readonly isTitleAutoGenerated = computed(() => this.currentMeeting()?.isTitleAutoGenerated ?? false);

  // Analysis section header button state
  readonly analysisHasTranscript = computed(() => !!this.currentMeeting()?.transcriptContent);
  readonly analysisIsProcessing = computed(() => this.currentMeeting()?.status === 'Processing');
  readonly analysisHasResults = computed(() => {
    const m = this.currentMeeting();
    if (!m) return false;
    return !!m.summary?.trim() || parseJsonArray(m.keyPoints).length > 0 || parseJsonArray(m.decisions).length > 0 || m.status === 'Ready';
  });

  // Insights exclusion (inverted for positive framing in UI)
  readonly includeInInsights = computed(() => !(this.currentMeeting()?.excludeFromInsights ?? false));

  // Suggested tags state (dismissed tags tracked locally)
  private readonly dismissedSuggestedTags = signal<Set<string>>(new Set());

  readonly pendingSuggestedTags = computed(() => {
    const meeting = this.currentMeeting();
    if (!meeting?.suggestedTags) return [];
    const allSuggested = parseJsonArray(meeting.suggestedTags);
    const dismissed = this.dismissedSuggestedTags();
    const existingNames = new Set(meeting.tags.map(t => t.name.toLowerCase()));
    return allSuggested.filter(
      name => !dismissed.has(name.toLowerCase()) && !existingNames.has(name.toLowerCase())
    );
  });

  private isDestroyed = false;
  private pollingTimeoutId: ReturnType<typeof setTimeout> | null = null;

  readonly currentMeeting = computed(() => {
    const id = this.meetingId();
    if (!id) return null;
    return this.meetingService.meetings().find(m => m.id === id) ?? null;
  });

  readonly displayTitle = computed(() => this.title() || 'Untitled');

  // Track action items count for status loading
  private readonly actionItemsCount = computed(() =>
    this.currentMeeting()?.actionItems.length ?? 0
  );

  // Tag computed properties
  readonly meetingTags = computed(() => this.currentMeeting()?.tags ?? []);

  // Collapsed summary computations (owned by parent to avoid reading child inputs before they're bound)
  readonly dateSummary = computed(() => {
    const date = this.meetingDate();
    if (!date) return 'No date set';
    return formatShortDate(date);
  });

  readonly timeSummary = computed(() => this.selectedTimeLabel());

  readonly attendeesSummary = computed(() => {
    const val = this.attendees();
    if (!val?.trim()) return 'No attendees';
    const names = val.split(',').map(s => s.trim()).filter(Boolean);
    if (names.length <= 2) return names.join(', ');
    return `${names[0]}, ${names[1]} +${names.length - 2}`;
  });

  readonly tagCountSummary = computed(() => {
    const count = this.meetingTags().length;
    if (count === 0) return '';
    return `${count} tag${count !== 1 ? 's' : ''}`;
  });

  protected readonly sourceBreadcrumb = signal<BreadcrumbItem>(
    { label: 'Meetings', icon: 'pi-arrow-left', route: '/meetings' }
  );

  constructor() {
    this.destroyRef.onDestroy(() => this.deleteConfirmation.cleanup());

    // Capture navigation state for dynamic breadcrumb (must be read during construction)
    const nav = this.router.getCurrentNavigation();
    const state = nav?.extras?.state as { breadcrumbSource?: BreadcrumbItem } | undefined;
    if (state?.breadcrumbSource) {
      this.sourceBreadcrumb.set({
        ...state.breadcrumbSource,
        icon: 'pi-arrow-left',
      });
    }

    // Reload action item statuses when action items count changes
    let lastActionItemCount = -1;
    effect(() => {
      const count = this.actionItemsCount();
      const id = this.meetingId();
      if (id && count > 0 && count !== lastActionItemCount) {
        lastActionItemCount = count;
        this.loadActionItemStatuses();
      }
    });

    // Update meetingDate when time label changes
    effect(() => {
      const timeLabel = this.selectedTimeLabel();
      const currentDate = this.meetingDate();
      const parsed = parseTimeInput(timeLabel);

      if (currentDate && parsed) {
        const newDate = new Date(currentDate);
        newDate.setHours(parsed.hours, parsed.minutes, 0, 0);
        if (newDate.getTime() !== currentDate.getTime()) {
          this.meetingDate.set(newDate);
          this.lastSaved.set(false);
          this.metadataChange$.next();
        }
      }
    });

    // Update breadcrumb when display title changes
    effect(() => {
      const title = this.displayTitle();
      this.headerService.breadcrumb.set([
        this.sourceBreadcrumb(),
        { label: title },
      ]);
    });

    // Auto-expand analysis section when results arrive
    let hadAnalysis = false;
    let lastMeetingId: string | null = null;
    effect(() => {
      const meeting = this.currentMeeting();
      const currentId = meeting?.id ?? null;
      // Reset tracking when navigating to a different meeting
      if (currentId !== lastMeetingId) {
        hadAnalysis = false;
        lastMeetingId = currentId;
      }
      const hasAnalysis = !!meeting?.summary || (meeting?.actionItems?.length ?? 0) > 0;
      if (hasAnalysis && !hadAnalysis) {
        this.analysisSection()?.expand();
      }
      hadAnalysis = hasAnalysis;
    });
  }

  ngAfterViewInit(): void {
    const tmpl = this.headerActions();
    if (tmpl) {
      this.headerService.actionsTemplate.set(tmpl);
    }
  }

  ngOnInit(): void {
    // Load tags
    if (this.tagService.tags().length === 0) {
      this.tagService.loadTags();
    }

    // Ensure meetings are loaded
    if (!this.meetingService.initialLoadComplete()) {
      this.meetingService.loadMeetings();
    }

    // Auto-save metadata with debounce
    this.metadataChange$
      .pipe(debounceTime(1000), takeUntil(this.destroy$))
      .subscribe(() => this.saveMetadata());

    // Auto-save transcript with debounce (longer delay for larger content)
    this.transcriptChange$
      .pipe(debounceTime(2000), takeUntil(this.destroy$))
      .subscribe(() => this.saveTranscript());

    // Get meeting ID from route
    this.route.paramMap.pipe(takeUntil(this.destroy$)).subscribe(params => {
      const id = params.get('id');
      if (id === 'new') {
        this.initNewMeeting();
      } else if (id) {
        this.loadMeeting(id);
      } else {
        this.notFound.set(true);
        this.loading.set(false);
      }
    });
  }

  ngOnDestroy(): void {
    this.isDestroyed = true;
    this.cancelPolling();
    // Close any open overlays to prevent orphaned popups
    this.detailsSectionRef()?.hideTimeSelect();
    this.showDatePicker.set(false);
    // Only stop recording/transcription if no active recording in progress
    if (!this.recorder.isActive()) {
      this.transcription.stop();
      this.recorder.discard();
    }
    this.headerService.clearContext();
    this.metadataChange$.complete();
    this.transcriptChange$.complete();
    this.destroy$.next();
    this.destroy$.complete();
  }

  private cancelPolling(): void {
    if (this.pollingTimeoutId !== null) {
      clearTimeout(this.pollingTimeoutId);
      this.pollingTimeoutId = null;
    }
  }

  @HostListener('document:keydown', ['$event'])
  onKeydown(event: KeyboardEvent): void {
    // Save with Cmd/Ctrl+S
    if ((event.metaKey || event.ctrlKey) && event.key === 's') {
      event.preventDefault();
      this.saveMetadata();
      this.saveTranscript();
    }

    // Escape: 3-step cascade
    if (event.key === 'Escape') {
      if (this.closeAnyOpenOverlay()) {
        event.preventDefault();
        return;
      }
      const target = event.target as HTMLElement | null;
      if (target && this.isEditableElement(target)) {
        target.blur();
        event.preventDefault();
        return;
      }
      this.navigateBack();
    }
  }

  private isEditableElement(el: HTMLElement): boolean {
    const editable = el.closest(
      'input, textarea, [contenteditable=""], [contenteditable="true"]'
    ) as HTMLElement | null;
    if (editable) return true;
    return el.isContentEditable;
  }

  private closeAnyOpenOverlay(): boolean {
    const details = this.detailsSectionRef();
    if (details) {
      if (details.isTimeSelectOpen()) {
        details.hideTimeSelect();
        return true;
      }
      if (this.showDatePicker()) {
        this.showDatePicker.set(false);
        return true;
      }
      if (details.isTagPickerOpen()) {
        details.closeTagPickerOverlay();
        return true;
      }
    }
    return false;
  }

  private initNewMeeting(): void {
    this.isNewMeeting.set(true);
    this.loading.set(false);
    this.notFound.set(false);
    this.meetingId.set(null);
    this.lastSaved.set(false);
    this.isSaving.set(false);
    this.title.set('');
    this.attendees.set('');
    this.transcript.set('');
    this.showTabWarning.set(false);
    this.actionItemStatuses.set([]);
    this.promotingIds.set(new Set());

    // Default to now at the nearest 30-min interval (users typically capture meetings that just happened)
    const defaultTime = getDefaultMeetingTime();
    const now = new Date();
    now.setHours(defaultTime.hours, defaultTime.minutes, 0, 0);
    this.meetingDate.set(now);
    this.selectedDateChip.set('Today');
    this.customDateLabel.set(null);
    this.selectedTimeLabel.set(formatTimeLabel(defaultTime.hours, defaultTime.minutes));

    // Collapse details for new meetings (smart defaults applied)
    setTimeout(() => {
      if (this.isDestroyed) return;
      this.detailsSection()?.collapse();
    });
  }

  private loadMeeting(id: string): void {
    this.cancelPolling();
    this.meetingId.set(id);
    this.loading.set(true);
    this.notFound.set(false);
    this.actionItemStatuses.set([]);
    this.promotingIds.set(new Set());

    // Resume recording UI if returning to the meeting that's being recorded
    if (this.recorder.isActive() && this.recorder.activeMeetingId() === id) {
      this.showTabWarning.set(true);
      this.recorder.onAudioChunk.set((blob) => this.transcription.sendAudio(blob));
    } else {
      this.showTabWarning.set(false);
    }

    let attempts = 0;
    const maxAttempts = 100;

    const checkForMeeting = () => {
      if (this.isDestroyed) return;
      attempts++;

      const meetings = this.meetingService.meetings();
      const meeting = meetings.find(m => m.id === id);

      if (meeting) {
        this.populateFromMeeting(meeting);
        this.loading.set(false);
      } else if (this.meetingService.initialLoadComplete()) {
        this.notFound.set(true);
        this.loading.set(false);
      } else if (attempts < maxAttempts) {
        this.pollingTimeoutId = setTimeout(checkForMeeting, 100);
      } else {
        this.notFound.set(true);
        this.loading.set(false);
      }
    };

    checkForMeeting();
  }

  private populateFromMeeting(meeting: Meeting): void {
    this.isNewMeeting.set(false);
    this.title.set(meeting.title ?? '');
    this.attendees.set(meeting.attendees ?? '');
    this.transcript.set(meeting.transcriptContent ?? '');
    this.dismissedSuggestedTags.set(new Set());

    const meetingDate = meeting.meetingDate ? new Date(meeting.meetingDate) : new Date();
    this.meetingDate.set(meetingDate);
    this.extractTimeFromDate(meetingDate);
    this.determineInitialDateChip(meetingDate);

    // Collapse details for existing meetings (focus on transcript)
    setTimeout(() => {
      if (this.isDestroyed) return;
      this.detailsSection()?.collapse();
    });
  }

  // --- Form change handlers ---

  onTitleChange(value: string): void {
    this.title.set(value);
    this.lastSaved.set(false);
    this.metadataChange$.next();
  }

  onAttendeesChange(value: string): void {
    this.attendees.set(value);
    this.lastSaved.set(false);
    this.metadataChange$.next();
  }

  onTranscriptChange(value: string): void {
    this.transcript.set(value);
    this.lastSaved.set(false);
    this.transcriptChange$.next();
  }

  acceptSuggestedTag(tagName: string): void {
    const id = this.meetingId();
    if (!id) return;
    const allTags = this.tagService.tags();
    const match = allTags.find(t => t.name.toLowerCase() === tagName.toLowerCase());
    if (match) {
      this.addTag({ id: match.id, name: match.name });
    } else {
      this.createAndAddTag(tagName);
    }
  }

  dismissSuggestedTag(tagName: string): void {
    this.dismissedSuggestedTags.update(set => {
      const newSet = new Set(set);
      newSet.add(tagName.toLowerCase());
      return newSet;
    });
  }

  onToggleExcludeFromInsights(): void {
    const id = this.meetingId();
    if (!id) return;
    const currentlyExcluded = this.currentMeeting()?.excludeFromInsights ?? false;
    this.meetingService.toggleExcludeFromInsights(id, !currentlyExcluded);
  }

  toggleDatePicker(): void {
    this.detailsSectionRef()?.hideTimeSelect();
    this.showDatePicker.set(!this.showDatePicker());
  }

  // --- Date/time helpers ---

  private addDays(date: Date, days: number): Date {
    const result = new Date(date);
    result.setDate(result.getDate() + days);
    return result;
  }

  selectDateOption(option: DateOption): void {
    this.selectedDateChip.set(option.label);
    this.customDateLabel.set(null);
    this.showDatePicker.set(false);

    const newDate = option.getValue();
    const currentDate = this.meetingDate();
    if (currentDate) {
      newDate.setHours(currentDate.getHours(), currentDate.getMinutes(), currentDate.getSeconds(), currentDate.getMilliseconds());
    } else {
      const parsed = parseTimeInput(this.selectedTimeLabel());
      if (parsed) {
        newDate.setHours(parsed.hours, parsed.minutes, 0, 0);
      } else {
        const defaultTime = getDefaultMeetingTime();
        newDate.setHours(defaultTime.hours, defaultTime.minutes, 0, 0);
      }
    }
    this.meetingDate.set(newDate);
    this.lastSaved.set(false);
    this.metadataChange$.next();
  }

  onDatePickerChange(date: Date): void {
    const newDate = new Date(date);
    const currentDate = this.meetingDate();
    if (currentDate) {
      newDate.setHours(currentDate.getHours(), currentDate.getMinutes(), currentDate.getSeconds(), currentDate.getMilliseconds());
    }
    this.meetingDate.set(newDate);
    this.selectedDateChip.set('custom');
    this.customDateLabel.set(formatShortDate(date));
    this.showDatePicker.set(false);
    this.lastSaved.set(false);
    this.metadataChange$.next();
  }

  private extractTimeFromDate(date: Date): void {
    this.selectedTimeLabel.set(formatTimeLabel(date.getHours(), date.getMinutes()));
    this.timeInputInvalid.set(false);
  }

  onTimeChange(value: string): void {
    if (!value) {
      this.timeInputInvalid.set(false);
      return;
    }
    const parsed = parseTimeInput(value);
    if (parsed) {
      this.selectedTimeLabel.set(formatTimeLabel(parsed.hours, parsed.minutes));
      this.timeInputInvalid.set(false);
    } else {
      this.selectedTimeLabel.set(value);
      this.timeInputInvalid.set(value.trim().length > 0);
    }
  }

  private determineInitialDateChip(date: Date): void {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const tomorrow = this.addDays(today, 1);
    const nextWeek = this.addDays(today, 7);
    const dateOnly = new Date(date);
    dateOnly.setHours(0, 0, 0, 0);

    if (dateOnly.getTime() === today.getTime()) {
      this.selectedDateChip.set('Today');
      this.customDateLabel.set(null);
    } else if (dateOnly.getTime() === tomorrow.getTime()) {
      this.selectedDateChip.set('Tomorrow');
      this.customDateLabel.set(null);
    } else if (dateOnly.getTime() === nextWeek.getTime()) {
      this.selectedDateChip.set('Next Week');
      this.customDateLabel.set(null);
    } else {
      this.selectedDateChip.set('custom');
      this.customDateLabel.set(formatShortDate(date));
    }
  }

  // --- Save helpers ---

  private saveMetadata(): void {
    if (this.isNewMeeting()) {
      this.createNewMeeting();
      return;
    }

    const id = this.meetingId();
    if (!id) return;

    this.isSaving.set(true);
    const date = this.meetingDate();
    this.meetingService.updateMeeting(
      id,
      this.title() || undefined,
      date ? toLocalISOString(date) : undefined,
      this.attendees() || undefined,
    );

    setTimeout(() => {
      this.isSaving.set(false);
      this.lastSaved.set(true);
    }, 300);
  }

  private saveTranscript(): void {
    const id = this.meetingId();
    if (!id || this.isNewMeeting()) return;

    const meeting = this.currentMeeting();
    const currentTranscript = this.transcript();

    if (currentTranscript && currentTranscript !== meeting?.transcriptContent) {
      this.meetingService.submitTranscript(id, currentTranscript);
    } else if (!currentTranscript && meeting?.transcriptContent) {
      this.meetingService.clearTranscript(id);
    }
  }

  private isCreating = false;

  private createNewMeeting(): void {
    if (this.isCreating) return;
    this.isCreating = true;
    this.isNewMeeting.set(false);
    this.isSaving.set(true);

    const date = this.meetingDate();
    this.meetingService.createMeeting(
      this.title() || undefined,
      date ? toLocalISOString(date) : undefined,
      this.attendees() || undefined,
      (realId) => {
        this.isCreating = false;
        if (this.isDestroyed) return;
        this.meetingId.set(realId);
        this.router.navigate(['/meetings', realId], { replaceUrl: true });
        this.isSaving.set(false);
        this.lastSaved.set(true);
      },
      () => {
        this.isCreating = false;
        if (!this.isDestroyed) {
          this.isNewMeeting.set(true);
          this.isSaving.set(false);
        }
      },
    );
  }

  // --- Audio recording with live transcription ---

  async startRecording(mode: 'microphone' | 'both' = 'microphone'): Promise<void> {
    if (this.recorder.isActive()) return;

    this.transcription.reset();

    const available = await this.transcription.checkAvailability();
    if (!available) {
      this.toast.error('Transcription service is unavailable. Recording was not started.');
      return;
    }

    if (mode === 'both') {
      await this.recorder.startWithSystemAudio();
    } else {
      await this.recorder.start();
    }

    if (this.recorder.isActive()) {
      this.recorder.activeMeetingId.set(this.meetingId());
      const firstName = this.auth.user()?.name?.trim().split(' ')[0];
      const userName = firstName || 'You';
      this.transcription.start(this.recorder.channelCount(), userName, this.recorder.mimeType());
      this.recorder.onAudioChunk.set((blob) => this.transcription.sendAudio(blob));
      this.showTabWarning.set(true);
    }
  }

  async stopRecording(): Promise<void> {
    try {
      this.recorder.onAudioChunk.set(null);
      this.transcription.stop();
      await this.recorder.stop();
      this.showTabWarning.set(false);

      const recognizedText = this.transcription.segments().length > 0
        ? this.transcription.labeledTranscript()
        : this.transcription.transcript();
      if (recognizedText) {
        const current = this.transcript();
        const separator = current ? '\n\n' : '';
        this.transcript.set(current + separator + recognizedText);
        this.transcriptChange$.next();
      }
    } catch (error) {
      this.recorder.onAudioChunk.set(null);
      this.transcription.stop();
      this.showTabWarning.set(false);
      console.error('Failed to stop audio recording:', error);
      this.toast.error('Failed to stop recording. Please try again.');
    }
  }

  // --- AI Analysis ---

  analyze(): void {
    const id = this.meetingId();
    if (id) {
      this.saveTranscript();
      this.meetingService.analyzeMeeting(id);
    }
  }

  toggleActionItem(actionItemId: string): void {
    const id = this.meetingId();
    if (id) {
      this.meetingService.toggleActionItem(id, actionItemId);
    }
  }

  promoteActionItem(actionItemId: string): void {
    const id = this.meetingId();
    if (!id) return;

    this.promotingIds.update(ids => new Set([...ids, actionItemId]));

    this.meetingService.promoteActionItem(id, actionItemId)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: result => {
          if (this.meetingId() !== id) return;
          this.toast.success({ summary: 'Task created', detail: result.title });
          this.loadActionItemStatuses();
          this.promotingIds.update(ids => {
            const newSet = new Set(ids);
            newSet.delete(actionItemId);
            return newSet;
          });
        },
        error: () => {
          if (this.isDestroyed) return;
          this.toast.error('Failed to promote action item');
          this.promotingIds.update(ids => {
            const newSet = new Set(ids);
            newSet.delete(actionItemId);
            return newSet;
          });
        },
      });
  }

  navigateToTask(taskId: string): void {
    this.router.navigate(['/tasks'], { queryParams: { highlight: taskId } });
  }

  private loadActionItemStatuses(): void {
    const id = this.meetingId();
    if (!id) return;

    this.meetingService.getActionItemStatus(id).subscribe({
      next: statuses => {
        if (this.meetingId() !== id) return;
        this.actionItemStatuses.set(statuses);
      },
      error: () => {
        if (this.meetingId() !== id) return;
        this.actionItemStatuses.set([]);
      },
    });
  }

  // --- Tags ---

  addTag(tag: MeetingTag): void {
    const id = this.meetingId();
    if (!id) return;
    if (this.meetingTags().some(t => t.id === tag.id)) return;
    this.meetingService.addTag(id, tag.id, tag.name);
    this.tagService.incrementUsageCount(tag.id, 'meeting');
  }

  removeTag(tagId: string): void {
    const id = this.meetingId();
    if (!id) return;
    this.meetingService.removeTag(id, tagId);
    this.tagService.decrementUsageCount(tagId, 'meeting');
  }

  createAndAddTag(name: string): void {
    this.tagService.createTag(name, (createdTag: Tag) => {
      this.addTag({ id: createdTag.id, name: createdTag.name });
    });
  }

  // --- Navigation ---

  navigateBack(): void {
    if (!this.lastSaved() && !this.isNewMeeting()) {
      this.saveMetadata();
      this.saveTranscript();
    }
    this.router.navigate([this.sourceBreadcrumb().route ?? '/meetings']);
  }

  startDeleteConfirm(): void {
    this.deleteConfirmation.cleanup();
    this.confirmingDelete.set(true);
    this.deleteConfirmation.start(() => {
      this.confirmingDelete.set(false);
    });
  }

  confirmDelete(): void {
    this.deleteConfirmation.cleanup();
    this.confirmingDelete.set(false);

    const id = this.meetingId();
    if (!id) return;

    const deleted = this.meetingService.deleteMeetingWithUndo(id);
    if (deleted) {
      this.toast.success({
        summary: 'Meeting deleted',
        action: {
          label: 'Undo',
          callback: () => this.meetingService.undoDelete(id),
        },
      });
      this.router.navigate([this.sourceBreadcrumb().route ?? '/meetings']);
    }
  }

  // --- Formatting helpers ---

  formatDate(dateString: string): string {
    const date = new Date(dateString);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 1) return 'just now';
    if (diffMins < 60) return `${diffMins} min ago`;
    if (diffHours < 24) return `${diffHours} hour${diffHours > 1 ? 's' : ''} ago`;
    if (diffDays < 7) return `${diffDays} day${diffDays > 1 ? 's' : ''} ago`;
    return date.toLocaleDateString();
  }

  asInput(event: Event): HTMLInputElement {
    return event.target as HTMLInputElement;
  }
}
