export type MeetingStatus = 'Draft' | 'Processing' | 'Ready' | 'Reviewed' | 'Failed';

export interface MeetingTag {
  id: string;
  name: string;
}

export interface ActionItem {
  id: string;
  description: string;
  assignee: string | null;
  isCompleted: boolean;
  createdAt: string;
}

export interface Meeting {
  id: string;
  title: string | null;
  isTitleAutoGenerated: boolean;
  meetingDate: string | null;
  attendees: string | null;
  transcriptContent: string | null;
  status: MeetingStatus;
  summary: string | null;
  keyPoints: string | null;
  decisions: string | null;
  suggestedTags: string | null;
  noteId: string | null;
  tags: MeetingTag[];
  actionItems: ActionItem[];
  createdAt: string;
  updatedAt: string;
}

export function parseJsonArray(json: string | null): string[] {
  if (!json) return [];
  try {
    const parsed = JSON.parse(json);
    if (!Array.isArray(parsed)) return [];
    return parsed.filter((item): item is string => typeof item === 'string');
  } catch {
    return [];
  }
}

/** Whether a meeting has any analysis results (summary, key points, decisions, or Ready status). */
export function hasAnalysisResults(meeting: Meeting | null | undefined): boolean {
  if (!meeting) return false;
  return !!meeting.summary?.trim() ||
    parseJsonArray(meeting.keyPoints).length > 0 ||
    parseJsonArray(meeting.decisions).length > 0 ||
    meeting.status === 'Ready';
}

export interface MeetingGroup {
  label: string;
  subLabel: string;
  meetings: Meeting[];
}

export interface ActionItemStatus {
  actionItemId: string;
  isLinked: boolean;
  taskId: string | null;
  taskStatus: 'Todo' | 'InProgress' | 'Done' | null;
}

export interface PromoteActionItemResult {
  taskId: string;
  title: string;
  status: string;
}
