import { Component, ChangeDetectionStrategy, input, output } from '@angular/core';
import { Meeting, MeetingStatus } from './meeting.model';
import { formatTime as sharedFormatTime, formatAmPm as sharedFormatAmPm } from '../shared/date-utils';

@Component({
  selector: 'app-meeting-row',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      class="meeting-row group cursor-pointer flex items-center gap-4 p-3 bg-surface-subtle border border-border rounded-lg hover:shadow-md active:scale-[0.995] active:bg-surface-muted/50 transition-all"
      [class.recording]="meeting().status === 'Processing' && !meeting().transcriptContent"
      [class.analyzing]="meeting().status === 'Processing' && meeting().transcriptContent"
      (click)="onOpen.emit()"
    >
      <!-- Time -->
      <div class="text-center w-14 flex-shrink-0">
        <div class="text-lg font-semibold text-foreground">{{ formatTime(meeting().meetingDate) }}</div>
        <div class="text-xs text-foreground-muted">{{ formatAmPm(meeting().meetingDate) }}</div>
      </div>

      <!-- Content -->
      <div class="flex-1 min-w-0">
        <div class="flex items-center gap-2">
          <h4 class="font-medium text-foreground text-sm truncate">
            {{ meeting().title || 'Untitled Meeting' }}
          </h4>
          @if (meeting().isTitleAutoGenerated) {
            <i class="pi pi-sparkles text-xs text-foreground-muted" title="AI-generated title"></i>
          }
          @if (meeting().transcriptContent) {
            <i class="pi pi-file-edit text-xs text-foreground-muted" title="Has transcript"></i>
          }
          @if (meeting().excludeFromInsights) {
            <i class="pi pi-eye-slash text-xs text-foreground-muted" title="Excluded from insights"></i>
          }
          <!-- Tags -->
          @if (meeting().tags.length > 0) {
            <div class="flex items-center gap-1">
              @for (tag of meeting().tags.slice(0, 3); track tag.id) {
                <span class="tag-badge">{{ tag.name }}</span>
              }
              @if (meeting().tags.length > 3) {
                <span class="text-xs text-foreground-muted">+{{ meeting().tags.length - 3 }}</span>
              }
            </div>
          }
        </div>
        @if (!meeting().title) {
          <p class="text-xs text-foreground-muted truncate">
            @if (meeting().transcriptContent) {
              <em>{{ getTranscriptPreview(meeting().transcriptContent!) }}</em>
            } @else {
              {{ getRelativeCreationTime(meeting().createdAt) }}
            }
          </p>
        } @else {
          <p class="text-xs text-foreground-muted truncate">
            {{ formatAttendees(meeting().attendees) }}
          </p>
        }
      </div>

      <!-- Status & Actions -->
      <div class="flex items-center gap-2">
        <span class="status-badge {{ getStatusClass(meeting().status) }}">
          @if (meeting().status === 'Processing' && !meeting().transcriptContent) {
            <span class="w-2 h-2 bg-current rounded-full animate-pulse mr-1"></span>
          } @else if (meeting().status === 'Processing' && meeting().transcriptContent) {
            <i class="pi pi-spin pi-spinner text-xs mr-1" aria-hidden="true"></i>
          } @else {
            <i class="{{ getStatusIcon(meeting().status) }} text-xs mr-1" aria-hidden="true"></i>
          }
          {{ getStatusLabel() }}
        </span>

        <!-- Delete button: mobile (always visible) -->
        <button
          type="button"
          class="flex md:hidden p-1.5 text-foreground-muted hover:text-danger hover:bg-danger/10 rounded transition-all"
          (click)="handleDelete($event)"
          aria-label="Delete meeting"
        >
          <i class="pi pi-trash text-sm"></i>
        </button>
        <!-- Delete button: desktop (hover-reveal) -->
        <button
          type="button"
          class="hidden md:group-hover:flex p-1.5 text-foreground-muted hover:text-danger hover:bg-danger/10 rounded transition-all"
          (click)="handleDelete($event)"
          aria-label="Delete meeting"
        >
          <i class="pi pi-trash text-sm"></i>
        </button>
      </div>
    </div>
  `,
  styles: [`
    .meeting-row.recording {
      border: 2px dashed var(--color-inprogress-text);
      background: var(--color-inprogress-bg);
    }

    .meeting-row.analyzing {
      border: 1px solid var(--color-inprogress-text);
      background: var(--color-inprogress-bg);
    }

    .status-badge {
      font-size: 10px;
      padding: 2px 8px;
      border-radius: 9999px;
      font-weight: 500;
      display: flex;
      align-items: center;
    }

    .status-draft {
      background: var(--color-todo-bg);
      color: var(--color-todo-text);
    }

    .status-processing {
      background: var(--color-inprogress-bg);
      color: var(--color-inprogress-text);
    }

    .status-ready {
      background: var(--color-primary-bg);
      color: var(--color-primary-text);
    }

    .status-reviewed {
      background: var(--color-done-bg);
      color: var(--color-done-text);
    }

    .status-failed {
      background: var(--color-danger-bg, rgba(191, 97, 106, 0.1));
      color: var(--color-danger-base);
    }
  `],
})
export class MeetingRowComponent {
  readonly meeting = input.required<Meeting>();
  readonly onOpen = output<void>();
  readonly onDelete = output<void>();

  formatTime(dateStr: string | null): string {
    return sharedFormatTime(dateStr);
  }

  formatAmPm(dateStr: string | null): string {
    return sharedFormatAmPm(dateStr);
  }

  formatAttendees(attendees: string | null): string {
    if (!attendees) return 'No attendees';
    return attendees;
  }

  getStatusClass(status: MeetingStatus): string {
    const classes: Record<MeetingStatus, string> = {
      Draft: 'status-draft',
      Processing: 'status-processing',
      Ready: 'status-ready',
      Reviewed: 'status-reviewed',
      Failed: 'status-failed',
    };
    return classes[status];
  }

  getStatusLabel(): string {
    const meeting = this.meeting();
    if (meeting.status === 'Processing') {
      return meeting.transcriptContent ? 'Analyzing' : 'Recording';
    }
    const labels: Record<MeetingStatus, string> = {
      Draft: 'Needs Transcript',
      Processing: 'Processing',
      Ready: 'Analyzed',
      Reviewed: 'Reviewed',
      Failed: 'Failed',
    };
    return labels[meeting.status];
  }

  getStatusIcon(status: MeetingStatus): string {
    const icons: Record<MeetingStatus, string> = {
      Draft: 'pi pi-pencil',
      Processing: 'pi pi-spinner',
      Ready: 'pi pi-sparkles',
      Reviewed: 'pi pi-check-circle',
      Failed: 'pi pi-exclamation-triangle',
    };
    return icons[status];
  }

  getTranscriptPreview(transcript: string): string {
    const cleaned = transcript.trim().replace(/\s+/g, ' ');
    if (!cleaned) return 'Empty transcript';
    if (cleaned.length <= 60) return cleaned;
    return cleaned.slice(0, 60) + '...';
  }

  getRelativeCreationTime(createdAt: string): string {
    const date = new Date(createdAt);
    if (isNaN(date.getTime())) return 'Unknown date';
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 1) return 'Created just now';
    if (diffMins < 60) return `Created ${diffMins} min ago`;
    if (diffHours < 24) return `Created ${diffHours} hour${diffHours > 1 ? 's' : ''} ago`;
    if (diffDays < 7) return `Created ${diffDays} day${diffDays > 1 ? 's' : ''} ago`;
    return `Created ${date.toLocaleDateString()}`;
  }

  handleDelete(event: Event): void {
    event.stopPropagation();
    this.onDelete.emit();
  }
}
