using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PraxisNote.Infrastructure.Migrations.Data.FeatureNotifications
{
    public partial class AddNotificationAutoGeneratedMeetingTitles : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                INSERT INTO "FeatureNotifications" ("Type", "Title", "Summary", "IssueUrl", "CreatedAt")
                VALUES (
                    'Feature',
                    'Auto-generated meeting titles and tag suggestions',
                    'AI analysis now suggests a title for untitled meetings and recommends relevant tags you can accept or dismiss with one click.',
                    'https://github.com/garethbaumgart/praxis-note/pull/300',
                    '2026-01-31T08:00:00Z'
                );
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DELETE FROM "FeatureNotifications"
                WHERE "Title" = 'Auto-generated meeting titles and tag suggestions';
                """);
        }
    }
}
